# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e727cd46e5ec558c03a40f84f5e0ca472854370e7efff4c4c25761475f98c096e55c316ff8f6d650ea02f275e77833075137b52b92884aa33814d9c8b6729d4f

test:
  secret_key_base: 343e84f1d1516284c238917e5736cb7e692a6e57145735beea34459101d56c31a20dfad728888ec8cd9d82518d5eedc64d673fff2d9b926142bc6f7f1a91f3c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
